---
labels:
  io.hass.type: addon
  io.hass.version: "1.0.0"
args:
  BUILD_FROM: python:3.13-slim
  BUILD_VERSION: "1.0.0"
  BUILD_ARCH: "{{ .Arch }}"
  BUILD_DATE: "{{ .Date }}"
  BUILD_REF: "{{ .Sha }}"
  BUILD_REPOSITORY: "{{ .Repository }}"
  BUILD_VERSION: "{{ .Version }}" 