name: "GA Load Manager HA Add-on"
version: "1.0.0"
slug: "genetic_load_manager"
description: "Intelligent load management using genetic algorithms to optimize household energy consumption based on PV production, battery status, and electricity market prices"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8123/tcp: 8123
ingress: true
ingress_port: 8123
panel_icon: mdi:lightning-bolt
panel_title: "GA Load Manager"
panel_admin: false
options:
  pv_entity_id: "sensor.pv_power"
  forecast_entity_id: "sensor.pv_forecast"
  battery_soc_entity_id: "sensor.battery_soc"
  price_entity_id: "sensor.electricity_price"
  optimization_interval: 15
  enable_external_access: true
  external_port: 8123
  genetic_algorithm:
    population_size: 50
    generations: 100
    mutation_rate: 0.1
    crossover_rate: 0.8
schema:
  pv_entity_id: str
  forecast_entity_id: str
  battery_soc_entity_id: str
  price_entity_id: str
  optimization_interval: int
  enable_external_access: bool
  external_port: int
  genetic_algorithm:
    population_size: int
    generations: int
    mutation_rate: float
    crossover_rate: float 