# Services for Genetic Load Manager

run_optimization:
  description: Triggers the genetic algorithm to optimize the load schedule immediately.
  fields:
    population_size:
      description: Number of individuals in the population.
      example: 100
    generations:
      description: Number of generations to run.
      example: 200
    mutation_rate:
      description: Probability of mutation.
      example: 0.05
    crossover_rate:
      description: Probability of crossover.
      example: 0.8

start_optimization:
  description: Starts the periodic optimization process (every 15 minutes).

stop_optimization:
  description: Stops the periodic optimization process.

toggle_scheduler:
  description: Switches between genetic algorithm and rule-based scheduling.
  fields:
    mode:
      description: Scheduler mode to use.
      example: "genetic"
      selector:
        select:
          options: ["genetic", "rule-based"]
          default: "genetic"

optimize_loads:
  name: "Optimize Loads"
  description: "Trigger manual load optimization using genetic algorithm"
  fields:
    force:
      name: "Force Optimization"
      description: "Force optimization even if recently run"
      selector:
        boolean:
          default: false
    generations:
      name: "Generations"
      description: "Number of generations for this optimization run"
      selector:
        number:
          min: 10
          max: 500
          default: 100
          unit_of_measurement: "generations"

apply_schedule:
  name: "Apply Schedule"
  description: "Apply the current optimized schedule to loads"
  fields:
    schedule_id:
      name: "Schedule ID"
      description: "ID of the schedule to apply (optional)"
      selector:
        text:
          default: "current"
    confirm:
      name: "Confirm Action"
      description: "Confirm that you want to apply this schedule"
      selector:
        boolean:
          default: false

reset_optimization:
  name: "Reset Optimization"
  description: "Reset optimization statistics and schedule"
  fields:
    confirm:
      name: "Confirm Reset"
      description: "Confirm that you want to reset optimization"
      selector:
        boolean:
          default: false

control_load:
  name: "Control Load"
  description: "Directly control a specific load"
  fields:
    entity_id:
      name: "Entity ID"
      description: "The entity ID of the load to control"
      selector:
        entity:
          domain: switch
          multiple: false
    action:
      name: "Action"
      description: "Action to perform on the load"
      selector:
        select:
          options:
            - turn_on
            - turn_off
            - toggle
          default: turn_on
    priority:
      name: "Priority"
      description: "Priority level for this control action"
      selector:
        select:
          options:
            - low
            - normal
            - high
            - critical
          default: normal

get_optimization_status:
  name: "Get Optimization Status"
  description: "Get current optimization status and statistics"
  fields: {}

get_algorithm_logs:
  name: "Get Algorithm Logs"
  description: "Get genetic algorithm optimization logs"
  fields:
    level:
      name: "Log Level"
      description: "Filter logs by level"
      selector:
        select:
          options:
            - all
            - DEBUG
            - INFO
            - WARNING
            - ERROR
          default: all
    limit:
      name: "Log Limit"
      description: "Maximum number of log entries to return"
      selector:
        number:
          min: 1
          max: 100
          default: 50
          unit_of_measurement: "entries"

update_manageable_loads:
  name: "Update Manageable Loads"
  description: "Scan and update the list of manageable loads"
  fields:
    scan_switches:
      name: "Scan Switch Entities"
      description: "Scan for new switch entities"
      selector:
        boolean:
          default: true
    scan_lights:
      name: "Scan Light Entities"
      description: "Scan for light entities that can be controlled"
      selector:
        boolean:
          default: false
    custom_loads:
      name: "Custom Loads"
      description: "List of custom entity IDs to include"
      selector:
        target:
          entity:
            domain: switch
            multiple: true

set_optimization_parameters:
  name: "Set Optimization Parameters"
  description: "Update genetic algorithm parameters"
  fields:
    population_size:
      name: "Population Size"
      description: "Number of individuals in the population"
      selector:
        number:
          min: 10
          max: 200
          default: 50
          unit_of_measurement: "individuals"
    generations:
      name: "Generations"
      description: "Number of generations per optimization"
      selector:
        number:
          min: 10
          max: 500
          default: 100
          unit_of_measurement: "generations"
    mutation_rate:
      name: "Mutation Rate"
      description: "Probability of mutation per gene"
      selector:
        number:
          min: 0.01
          max: 0.5
          default: 0.1
          step: 0.01
    crossover_rate:
      name: "Crossover Rate"
      description: "Probability of crossover between parents"
      selector:
        number:
          min: 0.1
          max: 1.0
          default: 0.8
          step: 0.1

export_schedule:
  name: "Export Schedule"
  description: "Export the current optimized schedule"
  fields:
    format:
      name: "Export Format"
      description: "Format for the exported schedule"
      selector:
        select:
          options:
            - json
            - csv
            - yaml
          default: json
    include_metadata:
      name: "Include Metadata"
      description: "Include optimization metadata in export"
      selector:
        boolean:
          default: true

update_pricing_parameters:
  name: "Update Pricing Parameters"
  description: "Update indexed tariff pricing parameters"
  fields:
    mfrr:
      name: "Frequency Restoration Reserve"
      description: "MFRR component in €/MWh"
      selector:
        number:
          min: 0.0
          max: 10.0
          default: 1.94
          step: 0.01
          unit_of_measurement: "€/MWh"
    q:
      name: "Quality Component"
      description: "Quality component in €/MWh"
      selector:
        number:
          min: 0.0
          max: 100.0
          default: 30.0
          step: 0.1
          unit_of_measurement: "€/MWh"
    fp:
      name: "Fixed Percentage"
      description: "Fixed percentage multiplier"
      selector:
        number:
          min: 1.0
          max: 2.0
          default: 1.1674
          step: 0.0001
    tae:
      name: "Transmission Tariff"
      description: "Transmission and distribution tariff in €/MWh"
      selector:
        number:
          min: 0.0
          max: 200.0
          default: 60.0
          step: 0.1
          unit_of_measurement: "€/MWh"
    vat:
      name: "VAT Multiplier"
      description: "VAT multiplier (1.23 = 23%)"
      selector:
        number:
          min: 1.0
          max: 1.5
          default: 1.23
          step: 0.01
    peak_multiplier:
      name: "Peak Hours Multiplier"
      description: "Price multiplier for peak hours"
      selector:
        number:
          min: 1.0
          max: 2.0
          default: 1.2
          step: 0.1
    off_peak_multiplier:
      name: "Off-Peak Hours Multiplier"
      description: "Price multiplier for off-peak hours"
      selector:
        number:
          min: 0.5
          max: 1.0
          default: 0.8
          step: 0.1 