name: Build and Test Add-on

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-python313.txt
    
    - name: Test imports
      run: python test_python313.py
    
    - name: Test Flask app
      run: |
        python -c "from app import app; print('Flask app imports successfully')"
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.python313 -t genetic-load-manager:test .
    
    - name: Test Docker container
      run: |
        docker run --rm -d --name test-container -p 8123:8123 genetic-load-manager:test
        sleep 10
        curl -f http://localhost:8123/health || exit 1
        docker stop test-container 