# Services for Genetic Load Manager integration

start_optimization:
  name: Start Optimization
  description: Start the genetic algorithm optimization process
  fields:
    optimization_mode:
      name: Optimization Mode
      description: The optimization strategy to use
      selector:
        select:
          options:
            - cost_savings
            - comfort
            - battery_health
            - grid_stability
            - carbon_reduction
          default: cost_savings
    duration_hours:
      name: Duration (Hours)
      description: How long to run the optimization (0 = continuous)
      selector:
        number:
          min: 0
          max: 24
          step: 0.5
          default: 0
          unit_of_measurement: hours

stop_optimization:
  name: Stop Optimization
  description: Stop the currently running optimization process
  fields: {}

pause_optimization:
  name: Pause Optimization
  description: Pause the currently running optimization process
  fields: {}

resume_optimization:
  name: Resume Optimization
  description: Resume a paused optimization process
  fields: {}

run_single_optimization:
  name: Run Single Optimization
  description: Run a single optimization cycle and return results
  fields:
    optimization_mode:
      name: Optimization Mode
      description: The optimization strategy to use for this run
      selector:
        select:
          options:
            - cost_savings
            - comfort
            - battery_health
            - grid_stability
            - carbon_reduction
          default: cost_savings
    max_time_seconds:
      name: Maximum Time (Seconds)
      description: Maximum time to spend on this optimization
      selector:
        number:
          min: 30
          max: 600
          step: 30
          default: 300
          unit_of_measurement: seconds

update_parameters:
  name: Update Parameters
  description: Update the genetic algorithm parameters
  fields:
    population_size:
      name: Population Size
      description: Number of individuals in the population
      selector:
        number:
          min: 20
          max: 500
          step: 10
          default: 100
    generations:
      name: Generations
      description: Number of generations to evolve
      selector:
        number:
          min: 50
          max: 1000
          step: 50
          default: 200
    mutation_rate:
      name: Mutation Rate
      description: Probability of mutation (0.01 to 0.5)
      selector:
        number:
          min: 0.01
          max: 0.5
          step: 0.01
          default: 0.05
    crossover_rate:
      name: Crossover Rate
      description: Probability of crossover (0.1 to 1.0)
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.05
          default: 0.8

update_device_config:
  name: Update Device Configuration
  description: Update the configuration for controllable devices
  fields:
    device_entity_id:
      name: Device Entity ID
      description: The entity ID of the device to configure
      selector:
        entity:
          domain:
            - switch
            - climate
            - light
            - media_player
            - fan
            - humidifier
            - dehumidifier
    max_power:
      name: Maximum Power (kW)
      description: Maximum power consumption for this device
      selector:
        number:
          min: 0.1
          max: 20.0
          step: 0.1
          unit_of_measurement: kW
    priority:
      name: Priority
      description: Priority level for this device (1 = highest, 5 = lowest)
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
          default: "3"
    controllable:
      name: Controllable
      description: Whether this device can be controlled by the optimizer
      selector:
        boolean:
          default: true

update_battery_config:
  name: Update Battery Configuration
  description: Update the battery system configuration
  fields:
    capacity:
      name: Capacity (kWh)
      description: Battery capacity in kilowatt-hours
      selector:
        number:
          min: 1.0
          max: 100.0
          step: 0.5
          unit_of_measurement: kWh
    max_charge_rate:
      name: Max Charge Rate (kW)
      description: Maximum battery charging rate
      selector:
        number:
          min: 0.5
          max: 50.0
          step: 0.5
          unit_of_measurement: kW
    max_discharge_rate:
      name: Max Discharge Rate (kW)
      description: Maximum battery discharging rate
      selector:
        number:
          min: 0.5
          max: 50.0
          step: 0.5
          unit_of_measurement: kW
    target_soc:
      name: Target State of Charge (%)
      description: Target battery state of charge
      selector:
        number:
          min: 20
          max: 95
          step: 5
          unit_of_measurement: "%"

get_optimization_status:
  name: Get Optimization Status
  description: Get the current status and statistics of the optimization
  fields: {}

get_optimization_history:
  name: Get Optimization History
  description: Get the history of optimization runs and results
  fields:
    days:
      name: Number of Days
      description: Number of days of history to retrieve
      selector:
        number:
          min: 1
          max: 30
          step: 1
          default: 7
          unit_of_measurement: days
    include_details:
      name: Include Details
      description: Whether to include detailed optimization data
      selector:
        boolean:
          default: false

export_optimization_data:
  name: Export Optimization Data
  description: Export optimization data to a file
  fields:
    format:
      name: Export Format
      description: The format to export the data in
      selector:
        select:
          options:
            - json
            - csv
            - excel
          default: json
    include_raw_data:
      name: Include Raw Data
      description: Whether to include raw optimization data
      selector:
        boolean:
          default: false
    filename:
      name: Filename
      description: Custom filename for the export (optional)
      selector:
        text:
          placeholder: optimization_export

import_optimization_data:
  name: Import Optimization Data
  description: Import optimization data from a file
  fields:
    file_path:
      name: File Path
      description: Path to the file to import
      selector:
        text:
          placeholder: /config/genetic_load_manager/export.json
    merge_existing:
      name: Merge with Existing
      description: Whether to merge with existing data or replace it
      selector:
        boolean:
          default: true

reset_optimization_data:
  name: Reset Optimization Data
  description: Reset all optimization data and start fresh
  fields:
    confirm:
      name: Confirm Reset
      description: Type 'RESET' to confirm you want to reset all data
      selector:
        text:
          placeholder: RESET

test_optimization:
  name: Test Optimization
  description: Run a test optimization with current settings
  fields:
    test_scenario:
      name: Test Scenario
      description: The scenario to test
      selector:
        select:
          options:
            - normal_day
            - high_solar
            - low_solar
            - peak_pricing
            - off_peak_pricing
            - battery_low
            - battery_high
          default: normal_day
    duration_hours:
      name: Duration (Hours)
      description: How long to simulate
      selector:
        number:
          min: 1
          max: 24
          step: 1
          default: 24
          unit_of_measurement: hours 

genetic_load_manager:
  get_full_schedule:
    name: "Get Full Schedule Data"
    description: "Retrieve the complete schedule data when attributes are truncated"
    fields:
      target:
        name: "Target"
        description: "The target to get schedule data for"
        selector:
          target:
            entity:
              domain: sensor
              device_class: energy
        required: true
      data_type:
        name: "Data Type"
        description: "Type of schedule data to retrieve"
        selector:
          select:
            options:
              - "full_schedule"
              - "compressed_schedule"
              - "summary_only"
              - "device_schedule"
        default: "full_schedule"
      device_id:
        name: "Device ID"
        description: "Specific device ID to get schedule for (only for device_schedule type)"
        selector:
          number:
            min: 0
            max: 10
            step: 1
        required: false

  get_schedule_statistics:
    name: "Get Schedule Statistics"
    description: "Get statistical information about the current schedule"
    fields:
      target:
        name: "Target"
        description: "The target to get statistics for"
        selector:
          target:
            entity:
              domain: sensor
              device_class: energy
        required: true 